### PR TITLE
Added french translation

### PR DESCRIPTION
**Pull request by bassdr**
My mother tongue, so it should be close enough :)

### CODE REVIEW

**Comment by bassdr** [comment]
I can't translate the "Basic" and "Advanced" strings, https://github.com/ufodone/envisalink_new/pull/148/commits/10db4ff786e801b15209a7c542d5f6e7f82af49c does not work.

**Comment by ufodone** [comment]
> I can't translate the "Basic" and "Advanced" strings, [10db4ff](https://github.com/ufodone/envisalink_new/commit/10db4ff786e801b15209a7c542d5f6e7f82af49c) does not work.

There was an issue with the way the menu was being initialized so it wasn't using the translations.  I've submitted a fix for this to main.

**Comment by bassdr** [comment]
Thanks! I tested your fix and it works fine now

**Comment by ufodone** [comment]
Thanks for this!

**Pull request merged**
