### PR TITLE
Use Honeywell keypad update reports to maintain partition and zone status

### PR DESCRIPTION
**Pull request by philh30**
For Honeywell panels, keypad updates (%02 reports) are now used to track zone and partition status.
- Zones are closed immediately when the partition they are assigned to closes. This provides very fast zone closure when a single zone is faulted.
- Zone timers are tracked to determine the number of keypad updates since the last reported zone fault. Separate timers are also maintained for zone tamper and battery warnings, which are also part of the keypad update queue. This will eventually allow tamper and battery status to be reported for individual zones.
- Zones are assumed closed when they have not reported as being faulted in a keypad update for a certain period. Currently the threshold is when the zone timer exceeds `2n+2`, where `n` is the number of active zone timers. This should reduce zone flapping when multiple zones are open.

Zone Timer Dumps are now ignored, and polling for them is not recommended. Other reports generated based on the Envisalink's logic (%01 and %02 reports) are also ignored.

### CODE REVIEW

**Comment by ufodone** [comment]
@philh30 Thanks for this!  

I see you've added a new callback for the keypad and I understand why given how the pyenvisalink code is structured but I'd ideally like to keep the callback patterns consistent between the Honeywell and DSC panels so it's simpler and more consistent for things using the library (like HA). I think that would mean separating the handlers from the callbacks and then having the handlers able to indicate which callbacks to trigger.

Let me take a pass at that and then I'll circle back here.  

Also FYI but I've been making most of the pyenvisalink changes initially over [here](https://github.com/ufodone/pyenvisalink/tree/command_queuing) and then manually bringing them back into this repo.  It's a bit of a hassle but allows me to avoid having to publish pyenvisalink package each time I make changes there.  I mention this mainly because I've got a pile of (mostly) linter changes sitting over there right now which unfortunately will probably make a bit of a mess of this PR.

**Comment by ufodone** [comment]
Hi @philh30, I've refactored the callback code in pyenvisalink and pulled it over to this repo.  You should be able to trigger all the necessary state change callbacks from `handle_keypad_update()` by populating a map with the necessary information. E.g. to trigger an update for partitions 1 and 3 and zones 1, 2 and 6 you can have `handle_keypad_update()` return:

```
{
    STATE_CHANGE_PARTITION: [1, 3],
    STATE_CHANGE_ZONE: [1, 2, 6],
}
```

There are additional constants for `STATE_CHANGE_ZONE_BYPASS` and `STATE_CHANGE_KEYPAD` that you can use as well.

I don't think you should need to update anything outside of `pyenvisalink` as I've got the integration wired up to handle the updates already.

Thanks!

**Comment by ufodone** [comment]
Also note that `main` has some other changes which reformat the EVL's MAC address to comply with HA's requirements which means when you upgrade you'll likely see duplicate devices (because the unique ID no longer matches).  I'd recommend just deleting them and then re-adding to resolve it.

**Comment by philh30** [comment]
Excellent - that should be easy to adapt to. Based on your workflow, I'm assuming you'd prefer canceling this PR and submitting in the command_queuing branch of the other repo?

**Comment by ufodone** [comment]
@philh30 I merged your changes into the latest codebase in (this)[https://github.com/ufodone/envisalink_new/tree/hw-keypad-updates] branch and did some basic testing with my mock server (since I don't have a Honeywell panel).

I see a bunch of TODO's in the code so not sure how much of that is necessary before some broader testing is necessary so if you could test it out with your own system and then let me know when you think it would be worth putting into a release for some broader testing.

Thanks!

**Comment by philh30** [comment]
Thanks! I haven't had a chance to get back to this as work is overwhelming my free time. Will test and let you know.

The TO DOs aren't necessary before testing - the core functionality of partition and zone status are all there, and I've been running my version for a while now with good results. A few of the TO DOs are to match (if necessary) a few data points the prior handlers were providing (entry delay status and ticks since last fault) that the new handler isn't. Others are real enhancements I'd like to see - zone bypass and zone battery status. Bypass in particular requires tracking which partition each zone is in, and I've been debating how to do that since the panel only provides that when a zone is tripped. I'm also still trying to think if there's better logic to avoid flutter on zones that are open long-term while clearing transient zones quicker.

**Comment by philh30** [comment]
That branch looks good. Attached log is putting it through a quick test this morning. I think it would be fine to push out for additional testing.

BTW, the labels for a few of the fields in the config flow are missing in that branch.

[home-assistant_2023-02-13T12-40-49.549Z.log](https://github.com/ufodone/envisalink_new/files/10722301/home-assistant_2023-02-13T12-40-49.549Z.log)

**Comment by ufodone** [comment]
Thanks, I'll get a new release posted later to others can try it out.

>BTW, the labels for a few of the fields in the config flow are missing in that branch.

I don't think there's any difference in those between this branch and main.  But the browser caches the translation strings so you might need to explicitly reload the page or clear your browser cache to pick up the strings as I did add a bunch of new ones recently.

**Comment by ufodone** [comment]
Closing this out and I'll pull the changes from the hw-keypad-updates branch instead.

**Pull request closed without merging**
