### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Adam-North**
Update README file with instructions on how to install with HACS.

### CODE REVIEW

**Comment by rct** [comment]
This is a good start, but there is more detail needed because the integration was renamed from envisalink to envisalink_new.

The first question is whether the existing envisalink integration with manual config is installed or not. 

Off the top of my head, I think the instructions would be more straightforward if the updated integration was named envisalink like the original.  Then I think, (but haven't tested), the presence of the code in the custom_components directory would pull in the new integration that HACS put in custom_components.

**Comment by ufodone** [comment]
Hmm.. for some reason I didn't think a duplicate name worked.  I just gave it a quick try and at first glance it appears to work.    I probably had it like that previously because there would have been a version conflict on pyenvisalink but since this integrate has pyenvislink embedded (to avoid the conflict) that's not really an issue now.

I'm not sure how HA bootstraps the integrations but if it's deterministic and custom components always override the stock integration then I could look at renaming it.

**Comment by Adam-North** [comment]
You guys are quick. This was meant to be just supplemental for the people that didn't know they had to add a custom repository. I didn't intend to create a cohesive installation guide. I will probably add more later.

**Comment by ufodone** [comment]
Thanks @Adam-North.  I'll merge this one now and separately figure out if I can rename it to just `envisalink` as that would certainly simplify things.

**Comment by rct** [comment]
@ufodone
> I'm not sure how HA bootstraps the integrations but if it's deterministic and custom components always override the stock integration then I could look at renaming it.

I do believe for the integration it is intentionally deterministic. I'm not sure how much is documented. I played with this a bit maybe one to two years ago when debugging some integration.

The modules used by the integration were a little trickier and I don't remember all the details. I think maybe a key was explicitly a higher version number in the manifest. 

One useful and interesting thing I learned that wasn't documented, the Hass loader will start looking at the level of the config directory first. So it is possible (at least at the time) to override any module that Hass uses by placing an updated copy at that level.  So when I was struggling to get the custom component to pick up the right module, I put a copy in `config`.  Later I got it working without that. 

I can't remember if just having the newer copy of the module in the integration directory worked or was ignored until the manifest explicitly asked for the updated version.

**Pull request merged**
